---
title: "Scatterplots_AWdataprep"
author: "Bongai Simango"
date: "24/01/2019"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r}
# Created by Bo Simango
# M.Sc. candidate 
# Supervisor: Dr. Daniel Fuller
# Memorial University of Newfoundland

# Data source: Health Data Collector App - AW data 
# Output: ggplot/scatter plot 

# First install knitr library
# Knitr allows you to manipulate data 
```

```{r}
library(knitr)
library(haven)
library(ggplot2)
```

```{r}
# Set working directory
setwd("C:/Thesis")
applewatch <- read.csv("health-data-Default.csv")
```

```{r}
# Read Health Data Collector App data 
applewatch <- read.csv("health-data-Default.csv")
```

```{r}
# Summary of statistical descriptives of each variable 
summary(applewatch)
summary(applewatch$DateTime)
summary(applewatch$Heart)
summary(applewatch$Calories)
summary(applewatch$Steps)
summary(applewatch$Distance)
```

```{r}
#Scatterplot of Heart rate vs. Time 
scatter<- ggplot(applewatch, aes(x = DateTime, y = Heart)) + 
  geom_point() +
  xlab("Date and Time")+
  ylab("Heart rate")
  plot(scatter)
```
  
```{r}
#Scatterplot of Calories vs. Time 
  scatter<- ggplot(applewatch, aes(x = DateTime, y = Calories)) + 
    geom_point() +
    xlab("Date and Time")+
    ylab("Calories")
  plot(scatter)  
```

```{r}
#Scatterplot of Steps vs. Time 
  scatter<- ggplot(applewatch, aes(x = DateTime, y = Steps)) + 
    geom_point() +
    xlab("Date and Time")+
    ylab("Steps")
  plot(scatter)  
```

```{r}
#Scatterplot of Distance vs. Time 
  scatter<- ggplot(applewatch, aes(x = DateTime, y = Distance)) + 
    geom_point() +
    xlab("Date and Time")+
    ylab("Distance")
  plot(scatter)  
```


  